### ISSUE TITLE
Plugin can't be loaded on GitBucket 4.34.0

### ISSUE THREAD

**Issue by onukura** [kasancode/gitbucket-label-kanban-plugin#12]
Since I updated GB ver. from 4.33.0 to 4.34.0, this plugin does not work (does not appear on plugin list).
Here is error log.

GB is running on Docker.

```
gitbucket_1  | 01:00:03.025 [Thread-31] INFO  gitbucket.core.plugin.PluginRegistry - Initialize gitbucket-label-kanban-plugin-3.5.0.jar
gitbucket_1  | 01:00:03.065 [Thread-31] ERROR gitbucket.core.plugin.PluginRegistry - Error during plugin initialization: gitbucket-label-kanban-plugin-3.5.0.jar
gitbucket_1  | java.lang.reflect.InvocationTargetException: null
gitbucket_1  |  at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
gitbucket_1  |  at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
gitbucket_1  |  at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
gitbucket_1  |  at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
gitbucket_1  |  at gitbucket.core.plugin.PluginRegistry$.$anonfun$initialize$3(PluginRegistry.scala:291)
gitbucket_1  |  at gitbucket.core.plugin.PluginRegistry$.$anonfun$initialize$3$adapted(PluginRegistry.scala:283)
gitbucket_1  |  at scala.collection.immutable.List.foreach(List.scala:305)
gitbucket_1  |  at gitbucket.core.plugin.PluginRegistry$.initialize(PluginRegistry.scala:283)
gitbucket_1  |  at gitbucket.core.plugin.PluginRegistry$.reload(PluginRegistry.scala:208)
gitbucket_1  |  at gitbucket.core.plugin.PluginWatchThread$$anon$2.$anonfun$run$3(PluginRegistry.scala:451)
gitbucket_1  |  at gitbucket.core.plugin.PluginWatchThread$$anon$2.$anonfun$run$3$adapted(PluginRegistry.scala:449)
gitbucket_1  |  at com.github.takezoe.slick.blocking.BlockingJdbcProfile$BlockingAPI$BlockingDatabase.$anonfun$withTransaction$2(BlockingProfile.scala:207)
gitbucket_1  |  at slick.JdbcProfileBlockingSession$BlockingSession.withTransaction(TransactionalJdbcBackend.scala:26)
gitbucket_1  |  at com.github.takezoe.slick.blocking.BlockingJdbcProfile$BlockingAPI$BlockingDatabase.$anonfun$withTransaction$1(BlockingProfile.scala:207)
gitbucket_1  |  at com.github.takezoe.slick.blocking.BlockingJdbcProfile$BlockingAPI$BlockingDatabase.withSession(BlockingProfile.scala:200)
gitbucket_1  |  at com.github.takezoe.slick.blocking.BlockingJdbcProfile$BlockingAPI$BlockingDatabase.withTransaction(BlockingProfile.scala:207)
gitbucket_1  |  at gitbucket.core.plugin.PluginWatchThread$$anon$2.run(PluginRegistry.scala:449)
gitbucket_1  | Caused by: java.lang.AbstractMethodError: Method io/github/gitbucket/labelkanban/controller/LabelKanbanController.gitbucket$core$service$ActivityService$_setter_$gitbucket$core$service$ActivityService$$formats_$eq(Lorg/json4s/Formats;)V is abstract
gitbucket_1  |  at io.github.gitbucket.labelkanban.controller.LabelKanbanController.gitbucket$core$service$ActivityService$_setter_$gitbucket$core$service$ActivityService$$formats_$eq(LabelKanbanController.scala)
gitbucket_1  |  at gitbucket.core.service.ActivityService.$init$(ActivityService.scala:24)
gitbucket_1  |  at io.github.gitbucket.labelkanban.controller.LabelKanbanController.<init>(LabelKanbanController.scala:35)
gitbucket_1  |  at Plugin.<init>(Plugin.scala:40)
gitbucket_1  |  ... 17 common frames omitted
```

**Comment by onukura** [comment]
👍
